version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/djtest
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python manage.py test

      - store_artifacts:
          path: test-reports
          destination: test-reports
  deploy:
#    machine:
#      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "e7:32:3b:12:5f:46:6f:e2:71:c3:b3:ca:61:c6:65:63"
#      - run:
#          name: Deploy Over SSH
#          command: |
#            ssh $SSH_USER@$SSH_HOST "<remote deploy command>"
      - run: ssh -o StrictHostKeyChecking=no ark@35.228.217.64 "echo 'hi' > hi"
#      - run: ssh -o StrictHostKeyChecking=no ark@35.228.217.64 "cd /home/ark/djtest ; sudo git pull"
#      - run: ssh -o StrictHostKeyChecking=no ark@35.228.217.64 "sudo fuser 8000/tcp -k; ls"
#      - run: ssh -o StrictHostKeyChecking=no ark@35.228.217.64 "pip3 install -r /home/ark/djtest/requirements.txt"
#      - run: ssh -o StrictHostKeyChecking=no ark@35.228.217.64 "nohup /usr/bin/python3 /home/evv/djtest/manage.py runserver > logs.txt &"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master